"""
BrainDead Segmentation nodes — human/clothing parsing + the BD_Parts* pipeline.

CATEGORY: 🧠BrainDead/Segmentation

Primary pipeline (SAM3 + Lotus-2 + QwenVL → rebuild loop):
- BD_SAM3MultiPrompt   → multi-prompt grounded segmentation
- BD_PartsRefine       → IoU dedup of overlapping prompts
- BD_PartsBuilder      → build PARTS_BUNDLE from masks + image + depth
- BD_PartsCompose      → flatten bundle to single image
- BD_PartsExport       → per-tag PNG + composite + layered PSD

Auxiliary (legacy / different segmentation paths):
- BD_FashnHumanParser, BD_ATRHumanParser → HUMAN_PARSE_MAP
- BD_HumanParserMaskClean / Split / NamedMask / Preview
- BD_MaskResolver — categorical skin/clothes/accessories resolution
- BD_MaskFlatten, BD_PackChannels, BD_DerivePBR — asset prep
"""

from .fashn_parser import (
    FASHN_PARSER_NODES,
    FASHN_PARSER_DISPLAY_NAMES,
    FASHN_PARSER_V3_NODES,
)
from .atr_parser import (
    ATR_PARSER_NODES,
    ATR_PARSER_DISPLAY_NAMES,
    ATR_PARSER_V3_NODES,
)
from .cleanup import (
    CLEANUP_NODES,
    CLEANUP_DISPLAY_NAMES,
    CLEANUP_V3_NODES,
)
from .mask_split import (
    MASK_SPLIT_NODES,
    MASK_SPLIT_DISPLAY_NAMES,
    MASK_SPLIT_V3_NODES,
)
from .sam3_multiprompt import (
    SAM3_MULTIPROMPT_NODES,
    SAM3_MULTIPROMPT_DISPLAY_NAMES,
    SAM3_MULTIPROMPT_V3_NODES,
)
from .mask_resolver import (
    MASK_RESOLVER_NODES,
    MASK_RESOLVER_DISPLAY_NAMES,
    MASK_RESOLVER_V3_NODES,
)
from .mask_flatten import (
    MASK_FLATTEN_NODES,
    MASK_FLATTEN_DISPLAY_NAMES,
    MASK_FLATTEN_V3_NODES,
)
from .pack_channels import (
    PACK_CHANNELS_NODES,
    PACK_CHANNELS_DISPLAY_NAMES,
    PACK_CHANNELS_V3_NODES,
)
from .atlas_pack import (
    ATLAS_PACK_NODES,
    ATLAS_PACK_DISPLAY_NAMES,
    ATLAS_PACK_V3_NODES,
)
from .channel_merge import (
    CHANNEL_MERGE_NODES,
    CHANNEL_MERGE_DISPLAY_NAMES,
    CHANNEL_MERGE_V3_NODES,
)
from .unpack_channels import (
    UNPACK_CHANNELS_NODES,
    UNPACK_CHANNELS_DISPLAY_NAMES,
    UNPACK_CHANNELS_V3_NODES,
)
from .luminance_mask import (
    LUMINANCE_MASK_NODES,
    LUMINANCE_MASK_DISPLAY_NAMES,
    LUMINANCE_MASK_V3_NODES,
)
from .normalize_luma import (
    NORMALIZE_LUMA_NODES,
    NORMALIZE_LUMA_DISPLAY_NAMES,
    NORMALIZE_LUMA_V3_NODES,
)
from .center_median_luma import (
    CENTER_MEDIAN_LUMA_NODES,
    CENTER_MEDIAN_LUMA_DISPLAY_NAMES,
    CENTER_MEDIAN_LUMA_V3_NODES,
)
from .depth_to_shadow_map import (
    DEPTH_TO_SHADOW_MAP_NODES,
    DEPTH_TO_SHADOW_MAP_DISPLAY_NAMES,
    DEPTH_TO_SHADOW_MAP_V3_NODES,
)
from .color_extract import (
    COLOR_EXTRACT_NODES,
    COLOR_EXTRACT_DISPLAY_NAMES,
    COLOR_EXTRACT_V3_NODES,
)
from .derive_pbr import (
    DERIVE_PBR_NODES,
    DERIVE_PBR_DISPLAY_NAMES,
    DERIVE_PBR_V3_NODES,
)
from .parts_builder import (
    PARTS_BUILDER_NODES,
    PARTS_BUILDER_DISPLAY_NAMES,
    PARTS_BUILDER_V3_NODES,
)
from .parts_refine import (
    PARTS_REFINE_NODES,
    PARTS_REFINE_DISPLAY_NAMES,
    PARTS_REFINE_V3_NODES,
)
from .parts_compose import (
    PARTS_COMPOSE_NODES,
    PARTS_COMPOSE_DISPLAY_NAMES,
    PARTS_COMPOSE_V3_NODES,
)
from .parts_export import (
    PARTS_EXPORT_NODES,
    PARTS_EXPORT_DISPLAY_NAMES,
    PARTS_EXPORT_V3_NODES,
)
from .parts_batch_edit import (
    PARTS_BATCH_EDIT_NODES,
    PARTS_BATCH_EDIT_DISPLAY_NAMES,
    PARTS_BATCH_EDIT_V3_NODES,
)
from .image_to_greyscale import (
    IMAGE_TO_GREYSCALE_NODES,
    IMAGE_TO_GREYSCALE_DISPLAY_NAMES,
    IMAGE_TO_GREYSCALE_V3_NODES,
)
from .face_mask_mediapipe import (
    FACE_MASK_MP_NODES,
    FACE_MASK_MP_DISPLAY_NAMES,
    FACE_MASK_MP_V3_NODES,
)
from .mask_correlate import (
    MASK_CORRELATE_NODES,
    MASK_CORRELATE_DISPLAY_NAMES,
    MASK_CORRELATE_V3_NODES,
)
from .face_skin_refine import (
    FACE_SKIN_REFINE_NODES,
    FACE_SKIN_REFINE_DISPLAY_NAMES,
    FACE_SKIN_REFINE_V3_NODES,
)
from .face_socket_infill import (
    FACE_SOCKET_INFILL_NODES,
    FACE_SOCKET_INFILL_DISPLAY_NAMES,
    FACE_SOCKET_INFILL_V3_NODES,
)
from .face_mp_data_io import (
    FACE_MP_DATA_IO_NODES,
    FACE_MP_DATA_IO_DISPLAY_NAMES,
    FACE_MP_DATA_IO_V3_NODES,
)
from .face_mp_export import (
    FACE_MP_EXPORT_NODES,
    FACE_MP_EXPORT_DISPLAY_NAMES,
    FACE_MP_EXPORT_V3_NODES,
)
from .face_mp_sam3 import (
    FACE_MP_SAM3_NODES,
    FACE_MP_SAM3_DISPLAY_NAMES,
    FACE_MP_SAM3_V3_NODES,
)
from .mouth_parts import (
    MOUTH_PARTS_NODES,
    MOUTH_PARTS_DISPLAY_NAMES,
    MOUTH_PARTS_V3_NODES,
)
from .mask_color_fill import (
    MASK_COLOR_FILL_NODES,
    MASK_COLOR_FILL_DISPLAY_NAMES,
    MASK_COLOR_FILL_V3_NODES,
)
from .draw_rect import (
    DRAW_RECT_NODES,
    DRAW_RECT_DISPLAY_NAMES,
    DRAW_RECT_V3_NODES,
)
from .draw_ellipse import (
    DRAW_ELLIPSE_NODES,
    DRAW_ELLIPSE_DISPLAY_NAMES,
    DRAW_ELLIPSE_V3_NODES,
)
from .luma_stats import (
    LUMA_STATS_NODES,
    LUMA_STATS_DISPLAY_NAMES,
    LUMA_STATS_V3_NODES,
)
from .mask_fill_holes import (
    FILL_MASK_HOLES_NODES,
    FILL_MASK_HOLES_DISPLAY_NAMES,
    FILL_MASK_HOLES_V3_NODES,
)
from .crop_to_mask import (
    CROP_TO_MASK_NODES,
    CROP_TO_MASK_DISPLAY_NAMES,
    CROP_TO_MASK_V3_NODES,
)
from .remove_background import (
    REMOVE_BACKGROUND_NODES,
    REMOVE_BACKGROUND_DISPLAY_NAMES,
    REMOVE_BACKGROUND_V3_NODES,
)
from .mask_batch_index import (
    MASK_BATCH_INDEX_NODES,
    MASK_BATCH_INDEX_DISPLAY_NAMES,
    MASK_BATCH_INDEX_V3_NODES,
)
from .parts_underpaint import (
    PARTS_UNDERPAINT_NODES,
    PARTS_UNDERPAINT_DISPLAY_NAMES,
    PARTS_UNDERPAINT_V3_NODES,
)

SEGMENTATION_V3_NODES = [
    *FASHN_PARSER_V3_NODES,
    *ATR_PARSER_V3_NODES,
    *CLEANUP_V3_NODES,
    *MASK_SPLIT_V3_NODES,
    *SAM3_MULTIPROMPT_V3_NODES,
    *MASK_RESOLVER_V3_NODES,
    *MASK_FLATTEN_V3_NODES,
    *PACK_CHANNELS_V3_NODES,
    *ATLAS_PACK_V3_NODES,
    *CHANNEL_MERGE_V3_NODES,
    *UNPACK_CHANNELS_V3_NODES,
    *LUMINANCE_MASK_V3_NODES,
    *NORMALIZE_LUMA_V3_NODES,
    *CENTER_MEDIAN_LUMA_V3_NODES,
    *DEPTH_TO_SHADOW_MAP_V3_NODES,
    *COLOR_EXTRACT_V3_NODES,
    *DERIVE_PBR_V3_NODES,
    *PARTS_BUILDER_V3_NODES,
    *PARTS_REFINE_V3_NODES,
    *PARTS_COMPOSE_V3_NODES,
    *PARTS_EXPORT_V3_NODES,
    *PARTS_BATCH_EDIT_V3_NODES,
    *IMAGE_TO_GREYSCALE_V3_NODES,
    *FACE_MASK_MP_V3_NODES,
    *MASK_CORRELATE_V3_NODES,
    *FACE_SKIN_REFINE_V3_NODES,
    *FACE_SOCKET_INFILL_V3_NODES,
    *FACE_MP_DATA_IO_V3_NODES,
    *FACE_MP_EXPORT_V3_NODES,
    *FACE_MP_SAM3_V3_NODES,
    *MOUTH_PARTS_V3_NODES,
    *MASK_COLOR_FILL_V3_NODES,
    *DRAW_RECT_V3_NODES,
    *DRAW_ELLIPSE_V3_NODES,
    *LUMA_STATS_V3_NODES,
    *FILL_MASK_HOLES_V3_NODES,
    *CROP_TO_MASK_V3_NODES,
    *REMOVE_BACKGROUND_V3_NODES,
    *MASK_BATCH_INDEX_V3_NODES,
    *PARTS_UNDERPAINT_V3_NODES,
]

NODE_CLASS_MAPPINGS = {
    **FASHN_PARSER_NODES,
    **ATR_PARSER_NODES,
    **CLEANUP_NODES,
    **MASK_SPLIT_NODES,
    **SAM3_MULTIPROMPT_NODES,
    **MASK_RESOLVER_NODES,
    **MASK_FLATTEN_NODES,
    **PACK_CHANNELS_NODES,
    **ATLAS_PACK_NODES,
    **CHANNEL_MERGE_NODES,
    **UNPACK_CHANNELS_NODES,
    **LUMINANCE_MASK_NODES,
    **NORMALIZE_LUMA_NODES,
    **CENTER_MEDIAN_LUMA_NODES,
    **DEPTH_TO_SHADOW_MAP_NODES,
    **COLOR_EXTRACT_NODES,
    **DERIVE_PBR_NODES,
    **PARTS_BUILDER_NODES,
    **PARTS_REFINE_NODES,
    **PARTS_COMPOSE_NODES,
    **PARTS_EXPORT_NODES,
    **PARTS_BATCH_EDIT_NODES,
    **IMAGE_TO_GREYSCALE_NODES,
    **FACE_MASK_MP_NODES,
    **MASK_CORRELATE_NODES,
    **FACE_SKIN_REFINE_NODES,
    **FACE_SOCKET_INFILL_NODES,
    **FACE_MP_DATA_IO_NODES,
    **FACE_MP_EXPORT_NODES,
    **FACE_MP_SAM3_NODES,
    **MOUTH_PARTS_NODES,
    **MASK_COLOR_FILL_NODES,
    **DRAW_RECT_NODES,
    **DRAW_ELLIPSE_NODES,
    **LUMA_STATS_NODES,
    **FILL_MASK_HOLES_NODES,
    **CROP_TO_MASK_NODES,
    **REMOVE_BACKGROUND_NODES,
    **MASK_BATCH_INDEX_NODES,
    **PARTS_UNDERPAINT_NODES,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **FASHN_PARSER_DISPLAY_NAMES,
    **ATR_PARSER_DISPLAY_NAMES,
    **CLEANUP_DISPLAY_NAMES,
    **MASK_SPLIT_DISPLAY_NAMES,
    **SAM3_MULTIPROMPT_DISPLAY_NAMES,
    **MASK_RESOLVER_DISPLAY_NAMES,
    **MASK_FLATTEN_DISPLAY_NAMES,
    **PACK_CHANNELS_DISPLAY_NAMES,
    **ATLAS_PACK_DISPLAY_NAMES,
    **CHANNEL_MERGE_DISPLAY_NAMES,
    **UNPACK_CHANNELS_DISPLAY_NAMES,
    **LUMINANCE_MASK_DISPLAY_NAMES,
    **NORMALIZE_LUMA_DISPLAY_NAMES,
    **CENTER_MEDIAN_LUMA_DISPLAY_NAMES,
    **DEPTH_TO_SHADOW_MAP_DISPLAY_NAMES,
    **COLOR_EXTRACT_DISPLAY_NAMES,
    **DERIVE_PBR_DISPLAY_NAMES,
    **PARTS_BUILDER_DISPLAY_NAMES,
    **PARTS_REFINE_DISPLAY_NAMES,
    **PARTS_COMPOSE_DISPLAY_NAMES,
    **PARTS_EXPORT_DISPLAY_NAMES,
    **PARTS_BATCH_EDIT_DISPLAY_NAMES,
    **IMAGE_TO_GREYSCALE_DISPLAY_NAMES,
    **FACE_MASK_MP_DISPLAY_NAMES,
    **MASK_CORRELATE_DISPLAY_NAMES,
    **FACE_SKIN_REFINE_DISPLAY_NAMES,
    **FACE_SOCKET_INFILL_DISPLAY_NAMES,
    **FACE_MP_DATA_IO_DISPLAY_NAMES,
    **FACE_MP_EXPORT_DISPLAY_NAMES,
    **FACE_MP_SAM3_DISPLAY_NAMES,
    **MOUTH_PARTS_DISPLAY_NAMES,
    **MASK_COLOR_FILL_DISPLAY_NAMES,
    **DRAW_RECT_DISPLAY_NAMES,
    **DRAW_ELLIPSE_DISPLAY_NAMES,
    **LUMA_STATS_DISPLAY_NAMES,
    **FILL_MASK_HOLES_DISPLAY_NAMES,
    **CROP_TO_MASK_DISPLAY_NAMES,
    **REMOVE_BACKGROUND_DISPLAY_NAMES,
    **MASK_BATCH_INDEX_DISPLAY_NAMES,
    **PARTS_UNDERPAINT_DISPLAY_NAMES,
}
