#!/usr/bin/env python3
"""
Hermetic regression tests for workflow_to_api.py converter.

These tests verify the slot/link/widget ordering fix that addresses:
1. Links resolved by INPUT NAME (from schema), not by saved tslot index
2. widgets_values consumed in SCHEMA DECLARATION ORDER, not positional
3. Dynamic combo sub-widgets spliced in after their parent

Ground truth: api/BD-parts_builder.api.json, BD-parts_builder_kontext, BD-parts_pointclick
are generated by ComfyUI's own frontend export, so reproduce at 0 differences.
"""

import json
import sys
import unittest
from pathlib import Path

# Add tools/ to path for import
tools_dir = Path(__file__).parent.parent / "tools"
sys.path.insert(0, str(tools_dir))
from workflow_to_api import workflow_to_api, flatten_schema_inputs, is_widget_type


class MockObjectInfo:
    """Helper to build minimal object_info schemas for testing."""

    @staticmethod
    def make_node_schema(required_inputs, optional_inputs=None):
        schema = {"input": {"required": dict(required_inputs)}}
        if optional_inputs:
            schema["input"]["optional"] = dict(optional_inputs)
        return schema


class TestLinkResolutionByName(unittest.TestCase):
    """Verify links are resolved by input NAME, not by saved tslot index."""

    def test_link_resolved_by_name_not_tslot(self):
        """
        COB_PartsPrep_v01 scenario: BD_PartsBuilder node saves with stale tslot.
        The FIXED converter resolves by NAME, not index.

        Key point: link 22 has tslot=11 but targets input name="mask_labels".
        The converter uses NAME matching, so it correctly wires mask_labels to ["16", 1].
        The tslot value (11) is IGNORED - only the link ID and input name matter.
        """
        schema = MockObjectInfo.make_node_schema({
            "image": ["IMAGE"],
            "masks": ["MASK", {}],
            "depth_image": ["IMAGE"],
            "mask_labels": ["STRING"],
        })

        workflow = {
            "nodes": [{
                "id": 20,
                "type": "BD_PartsBuilder",
                "inputs": [
                    {"name": "image", "link": 6, "slot_index": 0},
                    {"name": "masks", "slot_index": 1},
                    {"name": "depth_image", "link": 25, "slot_index": 2},
                    {"name": "mask_labels", "link": 22, "slot_index": 11},
                ],
                "widgets_values": [],
            }],
            "links": [
                [6, 1, 0, 20, 0, "IMAGE"],
                [25, 18, 0, 20, 2, "MASK"],
                [22, 16, 1, 20, 11, "STRING"],
            ],
        }

        api = workflow_to_api(workflow, {"BD_PartsBuilder": schema})
        node_20 = api.get("20", {}).get("inputs", {})

        self.assertIn("image", node_20)
        self.assertEqual(node_20["image"], ["1", 0])
        self.assertNotIn("masks", node_20)
        self.assertIn("depth_image", node_20)
        self.assertEqual(node_20["depth_image"], ["18", 0])
        # FIXED: mask_labels IS present because link 22 targets it by NAME
        self.assertIn("mask_labels", node_20)
        self.assertEqual(node_20["mask_labels"], ["16", 1])

    def test_link_by_name_preserves_correct_wiring(self):
        """Verify that when a node reorders inputs, links still wire to correct names."""
        schema = MockObjectInfo.make_node_schema({
            "input_a": ["IMAGE"],
            "input_b": ["IMAGE"],
            "input_c": ["IMAGE"],
        })

        workflow = {
            "nodes": [{
                "id": 5,
                "type": "TestNode",
                "inputs": [
                    {"name": "input_c", "link": 3, "slot_index": 0},
                    {"name": "input_a", "link": 1, "slot_index": 1},
                    {"name": "input_b", "link": 2, "slot_index": 2},
                ],
                "widgets_values": [],
            }],
            "links": [
                [1, 10, 0, 5, 1, "IMAGE"],
                [2, 11, 0, 5, 2, "IMAGE"],
                [3, 12, 0, 5, 0, "IMAGE"],
            ],
        }

        api = workflow_to_api(workflow, {"TestNode": schema})
        node_5 = api["5"]["inputs"]

        self.assertEqual(node_5["input_a"], ["10", 0])
        self.assertEqual(node_5["input_b"], ["11", 0])
        self.assertEqual(node_5["input_c"], ["12", 0])


class TestWidgetConsumptionOrder(unittest.TestCase):
    """Verify widgets_values consumed in SCHEMA DECLARATION ORDER, not positional."""

    def test_widgets_consumed_in_schema_order(self):
        """widgets_values should be consumed in schema declaration order."""
        schema = MockObjectInfo.make_node_schema(
            required_inputs={
                "seed": ["INT", {"default": 0}],
                "steps": ["INT", {"default": 20}],
                "cfg": ["FLOAT", {"default": 7.5}],
            },
            optional_inputs={
                "optional_param": ["STRING", {"default": ""}],
            }
        )

        workflow = {
            "nodes": [{
                "id": 10,
                "type": "TestSampler",
                "inputs": [
                    {"name": "seed", "widget": {"name": "seed"}, "slot_index": 0},
                    {"name": "steps", "widget": {"name": "steps"}, "slot_index": 1},
                    {"name": "cfg", "widget": {"name": "cfg"}, "slot_index": 2},
                    {"name": "optional_param", "widget": {"name": "optional_param"}, "slot_index": 3},
                ],
                "widgets_values": [42, 30, 5.0, "test"],
            }],
            "links": [],
        }

        api = workflow_to_api(workflow, {"TestSampler": schema})
        node_10 = api["10"]["inputs"]

        self.assertEqual(node_10["seed"], 42)
        self.assertEqual(node_10["steps"], 30)
        self.assertEqual(node_10["cfg"], 5.0)
        self.assertEqual(node_10["optional_param"], "test")

    def test_widgets_with_linked_input_skip_widget_queue(self):
        """Linked inputs should NOT consume from widgets_values queue."""
        schema = MockObjectInfo.make_node_schema({
            "seed": ["INT", {"default": 0}],
            "external_model": ["MODEL"],
            "cfg": ["FLOAT", {"default": 7.5}],
        })

        workflow = {
            "nodes": [{
                "id": 15,
                "type": "TestLoader",
                "inputs": [
                    {"name": "seed", "widget": {"name": "seed"}, "slot_index": 0},
                    {"name": "external_model", "link": 99, "slot_index": 1},
                    {"name": "cfg", "widget": {"name": "cfg"}, "slot_index": 2},
                ],
                "widgets_values": [42, 7.5],
            }],
            "links": [[99, 50, 0, 15, 1, "MODEL"]],
        }

        api = workflow_to_api(workflow, {"TestLoader": schema})
        node_15 = api["15"]["inputs"]

        self.assertEqual(node_15["seed"], 42)
        self.assertEqual(node_15["external_model"], ["50", 0])
        self.assertEqual(node_15["cfg"], 7.5)


class TestDynamicComboExpansion(unittest.TestCase):
    """Verify dynamic combo sub-widgets are spliced in after their parent."""

    def test_flatten_schema_inputs_preserves_order(self):
        """flatten_schema_inputs returns inputs in declaration order."""
        schema = {
            "input": {
                "required": {
                    "req_a": ["IMAGE"],
                    "req_b": ["INT", {"default": 0}],
                },
                "optional": {
                    "opt_a": ["STRING", {"default": ""}],
                    "opt_b": ["FLOAT", {"default": 1.0}],
                }
            }
        }

        flat = flatten_schema_inputs(schema)

        self.assertEqual(len(flat), 4)
        self.assertEqual(flat[0][0], "req_a")
        self.assertEqual(flat[1][0], "req_b")
        self.assertEqual(flat[2][0], "opt_a")
        self.assertEqual(flat[3][0], "opt_b")

    def test_is_widget_type_detection(self):
        """Verify is_widget_type correctly identifies widget vs socket inputs."""
        self.assertTrue(is_widget_type(["INT", {"default": 0}]))
        self.assertTrue(is_widget_type(["FLOAT", {"default": 1.0}]))
        self.assertTrue(is_widget_type(["STRING", {"default": ""}]))
        self.assertTrue(is_widget_type(["BOOLEAN", {"default": False}]))
        self.assertTrue(is_widget_type([["option1", "option2"], {}]))

        self.assertFalse(is_widget_type(["IMAGE"]))
        self.assertFalse(is_widget_type(["MASK"]))
        self.assertFalse(is_widget_type(["MODEL"]))
        self.assertFalse(is_widget_type(["LATENT"]))


class TestRealWorkflowRegression(unittest.TestCase):
    """Regression tests against real ComfyUI workflow exports."""

    @classmethod
    def setUpClass(cls):
        cls.api_dir = tools_dir.parent / "api"
        cls.example_dir = tools_dir.parent / "example_workflows"
        cls.object_info = None

        cls.parts_builder_ui = None
        cls.parts_builder_api = None

        ui_path = cls.example_dir / "BD-parts_builder.json"
        api_path = cls.api_dir / "BD-parts_builder.api.json"

        if ui_path.exists():
            with open(ui_path) as f:
                cls.parts_builder_ui = json.load(f)

        if api_path.exists():
            with open(api_path) as f:
                cls.parts_builder_api = json.load(f)

        # Fetch object_info from running ComfyUI server
        try:
            import urllib.request
            with urllib.request.urlopen("http://127.0.0.1:8188/object_info", timeout=10) as r:
                cls.object_info = json.loads(r.read())
        except Exception:
            pass

    def test_parts_builder_node_count(self):
        """Verify converter produces same node count as ground truth."""
        if not self.parts_builder_api or not self.object_info:
            self.skipTest("BD-parts_builder.api.json or ComfyUI server not available")

        converted = workflow_to_api(self.parts_builder_ui, self.object_info)
        self.assertEqual(len(converted), len(self.parts_builder_api),
                        "Converted node count should match ground truth API export")

    def test_parts_builder_link_integrity(self):
        """Verify all links in converted output resolve to emitted nodes."""
        if not self.parts_builder_api or not self.object_info:
            self.skipTest("BD-parts_builder.api.json or ComfyUI server not available")

        converted = workflow_to_api(self.parts_builder_ui, self.object_info)
        emitted_ids = set(converted.keys())

        dangling = []
        for nid, node in converted.items():
            for inp, val in node.get("inputs", {}).items():
                if isinstance(val, list) and len(val) == 2 and isinstance(val[0], str):
                    if val[0] not in emitted_ids:
                        dangling.append((nid, inp, val[0]))

        self.assertEqual(len(dangling), 0,
                        f"Found {len(dangling)} dangling link refs: {dangling[:5]}")


class TestSubgraphHandling(unittest.TestCase):
    """Verify subgraph instance handling in converter."""

    def test_uuid_typed_nodes_skipped_without_expansion(self):
        """UUID-typed subgraph instance nodes are skipped (require expansion first)."""
        schema = MockObjectInfo.make_node_schema({"input": ["IMAGE"]})

        workflow = {
            "nodes": [{
                "id": "uuid-1234-5678",
                "type": "some-uuid-type",
                "inputs": [{"name": "input", "link": 1, "slot_index": 0}],
                "widgets_values": [],
            }],
            "links": [[1, 10, 0, "uuid-1234-5678", 0, "IMAGE"]],
        }

        api = workflow_to_api(workflow, {"TestNode": schema})
        self.assertNotIn("uuid-1234-5678", api)


def run_tests():
    loader = unittest.TestLoader()
    suite = unittest.TestSuite()
    suite.addTests(loader.loadTestsFromTestCase(TestLinkResolutionByName))
    suite.addTests(loader.loadTestsFromTestCase(TestWidgetConsumptionOrder))
    suite.addTests(loader.loadTestsFromTestCase(TestDynamicComboExpansion))
    suite.addTests(loader.loadTestsFromTestCase(TestRealWorkflowRegression))
    suite.addTests(loader.loadTestsFromTestCase(TestSubgraphHandling))
    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)
    return 0 if result.wasSuccessful() else 1


if __name__ == "__main__":
    sys.exit(run_tests())


class TestBDSAM3MultiPromptWidgetOrdering(unittest.TestCase):
    """
    Test the BD_SAM3MultiPrompt node 13 scenario from the ticket description.
    
    Ticket description states:
    "BD_SAM3MultiPrompt node 13 of the same workflow carries link 16 on prompts 
    while widgets_values[0] is still the prompt text. Consuming the queue only 
    for unlinked inputs read every later widget one slot early."
    
    This tests that linked inputs don't skip widget values for subsequent inputs.
    """

    def test_bd_sam3_multi_prompt_widget_order(self):
        """BD_SAM3MultiPrompt: linked 'prompts' input should not shift widget values."""
        # Simplified schema mimicking BD_SAM3MultiPrompt
        schema = MockObjectInfo.make_node_schema({
            "prompts": ["STRING"],  # Linked input
            "negative_prompts": ["STRING", {"default": ""}],  # Widget
            "combine_mode": ["STRING", {"default": "union"}],  # Widget  
            "vote_threshold": ["FLOAT", {"default": 0.5}],  # Widget
        })

        # Simulating: link 16 on prompts, widgets_values = ["my prompt", "neg", "union", 0.7]
        # OLD BUG: Reading widgets_values only for unlinked inputs would shift everything
        # FIXED: Linked inputs skip widget slot, widgets consumed in order
        workflow = {
            "nodes": [{
                "id": 13,
                "type": "BD_SAM3MultiPrompt",
                "inputs": [
                    {"name": "prompts", "link": 16, "slot_index": 0},
                    {"name": "negative_prompts", "widget": {"name": "negative_prompts"}, "slot_index": 1},
                    {"name": "combine_mode", "widget": {"name": "combine_mode"}, "slot_index": 2},
                    {"name": "vote_threshold", "widget": {"name": "vote_threshold"}, "slot_index": 3},
                ],
                "widgets_values": ["negative_text", "union", 0.7],  # prompts is linked, so only 3 widget values
            }],
            "links": [[16, 10, 0, 13, 0, "STRING"]],
        }

        api = workflow_to_api(workflow, {"BD_SAM3MultiPrompt": schema})
        node_13 = api["13"]["inputs"]

        # prompts gets the link
        self.assertEqual(node_13["prompts"], ["10", 0])
        # negative_prompts gets first widget value (NOT shifted)
        self.assertEqual(node_13["negative_prompts"], "negative_text")
        # combine_mode gets second widget value
        self.assertEqual(node_13["combine_mode"], "union")
        # vote_threshold gets third widget value
        self.assertEqual(node_13["vote_threshold"], 0.7)


class TestBDPartsExportBaseImageWidget(unittest.TestCase):
    """
    Test BD_PartsExport.base_image arriving as boolean True bug.
    
    Ticket description states:
    "Same cause behind BD_PartsExport.base_image arriving as the boolean True: 
    its link was dropped, so the widget queue filled the input instead."
    
    This tests that when a link is dropped, the widget value correctly fills the slot.
    """

    def test_bd_parts_export_base_image_widget_fallback(self):
        """BD_PartsExport: dropped link means widget value fills the slot."""
        schema = MockObjectInfo.make_node_schema({
            "parts_bundle": ["PARTS_BUNDLE"],
            "base_image": ["IMAGE", {}],  # Optional, may be linked or widget
            "filename": ["STRING", {"default": "output"}],
        })

        # base_image link was dropped (tslot out of range), widget True fills the slot
        workflow = {
            "nodes": [{
                "id": 30,
                "type": "BD_PartsExport",
                "inputs": [
                    {"name": "parts_bundle", "link": 30, "slot_index": 0},
                    {"name": "base_image", "slot_index": 1},  # Link dropped, will use widget
                    {"name": "filename", "widget": {"name": "filename"}, "slot_index": 2},
                ],
                "widgets_values": [True, "my_output.png"],  # base_image=True, filename="my_output.png"
            }],
            "links": [[30, 20, 0, 30, 0, "PARTS_BUNDLE"]],
        }

        api = workflow_to_api(workflow, {"BD_PartsExport": schema})
        node_30 = api["30"]["inputs"]

        self.assertEqual(node_30["parts_bundle"], ["20", 0])
        # base_image gets widget value True (the bug was this being True instead of an image link)
        self.assertEqual(node_30["base_image"], True)
        self.assertEqual(node_30["filename"], "my_output.png")


# Add new tests to the suite
if __name__ == "__main__":
    # Re-run with new tests appended
    loader = unittest.TestLoader()
    suite = unittest.TestSuite()
    suite.addTests(loader.loadTestsFromTestCase(TestLinkResolutionByName))
    suite.addTests(loader.loadTestsFromTestCase(TestWidgetConsumptionOrder))
    suite.addTests(loader.loadTestsFromTestCase(TestDynamicComboExpansion))
    suite.addTests(loader.loadTestsFromTestCase(TestRealWorkflowRegression))
    suite.addTests(loader.loadTestsFromTestCase(TestSubgraphHandling))
    suite.addTests(loader.loadTestsFromTestCase(TestBDSAM3MultiPromptWidgetOrdering))
    suite.addTests(loader.loadTestsFromTestCase(TestBDPartsExportBaseImageWidget))
    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)
    sys.exit(0 if result.wasSuccessful() else 1)
