"""
BrainDead FaceWrap — multi-view UV texture pipeline.

CATEGORY: 🧠BrainDead/FaceWrap

Pipeline (see docs/face-wrap.md):
- BD_FaceLandmarks       → MediaPipe FaceLandmarker on a 4-view batch
- BD_FaceFit             → assemble landmarks + canonical face mesh
- BD_FaceTextureBake     → per-view UV bake via nvdiffrast (future)
- BD_UVConfidenceBlend   → cosine-weighted composite + gap mask (future)
- BD_UVTransfer          → cross-mesh UV→UV warp for CC5/Metahuman (future)
"""

from .landmarks import (
    FACEWRAP_LANDMARKS_NODES,
    FACEWRAP_LANDMARKS_DISPLAY_NAMES,
    FACEWRAP_LANDMARKS_V3_NODES,
)
from .face_fit import (
    FACEWRAP_FACE_FIT_NODES,
    FACEWRAP_FACE_FIT_DISPLAY_NAMES,
    FACEWRAP_FACE_FIT_V3_NODES,
)
from .flame_fit import (
    FACEWRAP_FLAME_FIT_NODES,
    FACEWRAP_FLAME_FIT_DISPLAY_NAMES,
    FACEWRAP_FLAME_FIT_V3_NODES,
)
from .texture_bake import (
    FACEWRAP_TEXTURE_BAKE_NODES,
    FACEWRAP_TEXTURE_BAKE_DISPLAY_NAMES,
    FACEWRAP_TEXTURE_BAKE_V3_NODES,
)
from .confidence_blend import (
    FACEWRAP_BLEND_NODES,
    FACEWRAP_BLEND_DISPLAY_NAMES,
    FACEWRAP_BLEND_V3_NODES,
)
from .uv_transfer import (
    FACEWRAP_TRANSFER_NODES,
    FACEWRAP_TRANSFER_DISPLAY_NAMES,
    FACEWRAP_TRANSFER_V3_NODES,
)
from .qwen_composite import (
    FACEWRAP_QWEN_COMPOSITE_NODES,
    FACEWRAP_QWEN_COMPOSITE_DISPLAY_NAMES,
    FACEWRAP_QWEN_COMPOSITE_V3_NODES,
)
from .strip_stitch import (
    FACEWRAP_STRIP_NODES,
    FACEWRAP_STRIP_DISPLAY_NAMES,
    FACEWRAP_STRIP_V3_NODES,
)
from .mosaic_stitch import (
    FACEWRAP_MOSAIC_NODES,
    FACEWRAP_MOSAIC_DISPLAY_NAMES,
    FACEWRAP_MOSAIC_V3_NODES,
)

FACEWRAP_V3_NODES = [
    *FACEWRAP_LANDMARKS_V3_NODES,
    *FACEWRAP_FACE_FIT_V3_NODES,
    *FACEWRAP_FLAME_FIT_V3_NODES,
    *FACEWRAP_TEXTURE_BAKE_V3_NODES,
    *FACEWRAP_BLEND_V3_NODES,
    *FACEWRAP_TRANSFER_V3_NODES,
    *FACEWRAP_QWEN_COMPOSITE_V3_NODES,
    *FACEWRAP_STRIP_V3_NODES,
    *FACEWRAP_MOSAIC_V3_NODES,
]

NODE_CLASS_MAPPINGS = {
    **FACEWRAP_LANDMARKS_NODES,
    **FACEWRAP_FACE_FIT_NODES,
    **FACEWRAP_FLAME_FIT_NODES,
    **FACEWRAP_TEXTURE_BAKE_NODES,
    **FACEWRAP_BLEND_NODES,
    **FACEWRAP_TRANSFER_NODES,
    **FACEWRAP_QWEN_COMPOSITE_NODES,
    **FACEWRAP_STRIP_NODES,
    **FACEWRAP_MOSAIC_NODES,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **FACEWRAP_LANDMARKS_DISPLAY_NAMES,
    **FACEWRAP_FACE_FIT_DISPLAY_NAMES,
    **FACEWRAP_FLAME_FIT_DISPLAY_NAMES,
    **FACEWRAP_TEXTURE_BAKE_DISPLAY_NAMES,
    **FACEWRAP_BLEND_DISPLAY_NAMES,
    **FACEWRAP_TRANSFER_DISPLAY_NAMES,
    **FACEWRAP_QWEN_COMPOSITE_DISPLAY_NAMES,
    **FACEWRAP_STRIP_DISPLAY_NAMES,
    **FACEWRAP_MOSAIC_DISPLAY_NAMES,
}
